name: Deploy the application
on:
   push:
      branches:
         - dev
         - main
jobs:
   my_first_job:
      runs-on: ubuntu-latest
      steps:
         - run: echo "first job is running"
   my_second_job:
      runs-on: ubuntu-latest
      needs: my_first_job
      steps:
         - run: echo "second job is running"
